// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjLQcNCWcYWtBB8qKgW7UNAC6czd8jbIM',
    appId: '1:352465460942:web:449d8c2ce8d2d313e2fa9f',
    messagingSenderId: '352465460942',
    projectId: 'fir-auth-7b61c',
    authDomain: 'fir-auth-7b61c.firebaseapp.com',
    storageBucket: 'fir-auth-7b61c.appspot.com',
    measurementId: 'G-S32362LFL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMG-kLD0f9M1x4dFJWpVtYcxj-q-vp8EA',
    appId: '1:352465460942:android:3330477f42a900b7e2fa9f',
    messagingSenderId: '352465460942',
    projectId: 'fir-auth-7b61c',
    storageBucket: 'fir-auth-7b61c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtHHeY4pEiCiU9-NGemxDt9Ms4C5Cjfbo',
    appId: '1:352465460942:ios:9a3e4d814414eb9be2fa9f',
    messagingSenderId: '352465460942',
    projectId: 'fir-auth-7b61c',
    storageBucket: 'fir-auth-7b61c.appspot.com',
    iosBundleId: 'com.example.misLabs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtHHeY4pEiCiU9-NGemxDt9Ms4C5Cjfbo',
    appId: '1:352465460942:ios:bd401487d03a43b2e2fa9f',
    messagingSenderId: '352465460942',
    projectId: 'fir-auth-7b61c',
    storageBucket: 'fir-auth-7b61c.appspot.com',
    iosBundleId: 'com.example.misLabs.RunnerTests',
  );
}
